language: cpp

compiler:
  - gcc
  - clang

before_install:
  - uname -a
  - sudo apt-add-repository --yes ppa:sfttech/random # cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get remove -qq cmake # remove the museum edition (github.com/SFTtech/openage)
  - sudo apt-get install -qq cmake clang libboost-all-dev
  - sudo apt-get install apt-show-versions

before_script:
  - clang --version
  - gcc --version
  - apt-show-versions libboost-all-dev # Boost version
  - cmake --version

script:
  - mkdir -p travisbuild
  - cd travisbuild
  - cmake ..
  - make

notifications:
  irc:
    channels:
      - "chat.freenode.net#libircppclient"
    template:
      - "%{repository} (%{commit} - %{author}): %{message}"
      - "took %{duration}, moar info: %{build_url}"
    use_notice: true
    skip_join: true

cache:
  directories:
    - .cicache
  apt: true
